FROM rust:1.82 as builder

WORKDIR /app
COPY . .

RUN cargo fetch

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    libssl3 \
 && rm -rf /var/lib/apt/lists/*
 RUN apt-get update && apt-get install -y ca-certificates

WORKDIR /app

COPY --from=builder /app/target/release/api-fetch .
COPY --from=builder /app/target/release/redis .

RUN useradd -m appuser && chown -R appuser /app
USER appuser

CMD ["./api-fetch"]
