pub const ATTACHMENTS: [(&str, &str); 48] = [
    ("Item_Attach_Weapon_Lower_AngledForeGrip_C", "Angled Foregrip"),
    ("Item_Attach_Weapon_Lower_Foregrip_C", "Vertical Foregrip"),
    ("Item_Attach_Weapon_Lower_HalfGrip_C", "Half Grip"),
    ("Item_Attach_Weapon_Lower_LaserPointer_C", "Laser Sight"),
    ("Item_Attach_Weapon_Lower_LightweightForeGrip_C", "Light Grip"),
    ("Item_Attach_Weapon_Lower_QuickDraw_Large_Crossbow_C", "QuickDraw Crossbow Quiver"),
    ("Item_Attach_Weapon_Lower_ThumbGrip_C", "Thumb Grip"),
    ("Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Large_C", "Extended QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Medium_C", "Extended QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Small_C", "Extended QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_ExtendedQuickDraw_SniperRifle_C", "Extended QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_Extended_Large_C", "Extended Mag"),
    ("Item_Attach_Weapon_Magazine_Extended_Medium_C", "Extended Mag"),
    ("Item_Attach_Weapon_Magazine_Extended_Small_C", "Extended Mag"),
    ("Item_Attach_Weapon_Magazine_Extended_SniperRifle_C", "Extended Mag"),
    ("Item_Attach_Weapon_Magazine_QuickDraw_Large_C", "QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_QuickDraw_Medium_C", "QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_QuickDraw_Small_C", "QuickDraw Mag"),
    ("Item_Attach_Weapon_Magazine_QuickDraw_SniperRifle_C", "QuickDraw Mag"),
    ("Item_Attach_Weapon_Muzzle_Choke_C", "Choke"),
    ("Item_Attach_Weapon_Muzzle_Compensator_Large_C", "Compensator"),
    ("Item_Attach_Weapon_Muzzle_Compensator_Medium_C", "Compensator"),
    ("Item_Attach_Weapon_Muzzle_Compensator_SniperRifle_C", "Compensator"),
    ("Item_Attach_Weapon_Muzzle_Duckbill_C", "Duckbill"),
    ("Item_Attach_Weapon_Muzzle_FlashHider_Large_C", "Flash Hider"),
    ("Item_Attach_Weapon_Muzzle_FlashHider_Medium_C", "Flash Hider"),
    ("Item_Attach_Weapon_Muzzle_FlashHider_SniperRifle_C", "Flash Hider"),
    ("Item_Attach_Weapon_Muzzle_Suppressor_Large_C", "Suppressor"),
    ("Item_Attach_Weapon_Muzzle_Suppressor_Medium_C", "Suppressor"),
    ("Item_Attach_Weapon_Muzzle_Suppressor_Small_C", "Suppressor"),
    ("Item_Attach_Weapon_Muzzle_Suppressor_SniperRifle_C", "Suppressor"),
    ("Item_Attach_Weapon_SideRail_DotSight_RMR_C", "Canted Sight"),
    ("Item_Attach_Weapon_Stock_AR_Composite_C", "Tactical Stock"),
    ("Item_Attach_Weapon_Stock_AR_HeavyStock_C", "Heavy Stock"),
    ("Item_Attach_Weapon_Stock_Shotgun_BulletLoops_C", "Shotgun Bullet Loops"),
    ("Item_Attach_Weapon_Stock_SniperRifle_BulletLoops_C", "Sniper Rifle Bullet Loops"),
    ("Item_Attach_Weapon_Stock_SniperRifle_CheekPad_C", "Sniper Rifle Cheek Pad"),
    ("Item_Attach_Weapon_Stock_UZI_C", "Uzi Stock"),
    ("Item_Attach_Weapon_Upper_ACOG_01_C", "4x ACOG Scope"),
    ("Item_Attach_Weapon_Upper_Aimpoint_C", "2x Aimpoint Scope"),
    ("Item_Attach_Weapon_Upper_CQBSS_C", "8x Scope"),
    ("Item_Attach_Weapon_Upper_DotSight_01_C", "Red Dot Sight"),
    ("Item_Attach_Weapon_Upper_Holosight_C", "Holographic Sight"),
    ("Item_Attach_Weapon_Upper_PM2_01_C", "15x Scope"),
    ("Item_Attach_Weapon_Upper_Scope3x_C", "3x Scope"),
    ("Item_Attach_Weapon_Upper_Scope6x_C", "6x Scope"),
    ("Item_Attach_Weapon_Upper_Thermal_C", "Thermal Scope"),
    ("Item_Attach_Weapon_Muzzle_AR_MuzzleBrake_C", "Muzzle Brake"),
];
