pub const WEAPONS: [(&str, &str); 293] = [
    ("AIPawn_Base_Female_C", "AI"),
    ("AIPawn_Base_Male_C", "AI"),
    ("AirBoat_V2_C", "Airboat"),
    ("AquaRail_A_01_C", "Aquarail"),
    ("AquaRail_A_02_C", "Aquarail"),
    ("AquaRail_A_03_C", "Aquarail"),
    ("BP_ATV_C", "Quad"),
    ("BP_BearV2_C", "Bear"),
    ("BP_BRDM_C", "BRDM-2"),
    ("BP_Bicycle_C", "Mountain Bike"),
    ("BP_Blanc_C", "Blanc"),
    ("BP_CoupeRB_C", "Volle"),
    ("BP_DO_Circle_Train_Merged_C", "Train"),
    ("BP_DO_Line_Train_Dino_Merged_C", "Train"),
    ("BP_DO_Line_Train_Merged_C", "Train"),
    ("BP_Dirtbike_C", "Pärrä"),
    ("BP_DronePackage_Projectile_C", "Drone"),
    ("BP_Eragel_CargoShip01_C", "Ferry"),
    ("BP_FakeLootProj_AmmoBox_C", "Loot Truck"),
    ("BP_FakeLootProj_MilitaryCrate_C", "Loot Truck"),
    ("BP_FireEffectController_C", "Molotov Fire"),
    ("BP_FireEffectController_JerryCan_C", "Jerrycan Fire"),
    ("BP_Food_Truck_C", "Food Truck"),
    ("BP_Helicopter_C", "Pillar Scout Helicopter"),
    ("BP_IncendiaryDebuff_C", "Burn"),
    ("BP_JerryCanFireDebuff_C", "Burn"),
    ("BP_JerryCan_FuelPuddle_C", "Burn"),
    ("BP_KillTruck_C", "Truck"),
    ("BP_LootTruck_C", "Truck"),
    ("BP_M_Rony_A_01_C", "Rony"),
    ("BP_M_Rony_A_02_C", "Rony"),
    ("BP_M_Rony_A_03_C", "Rony"),
    ("BP_Mirado_A_02_C", "Mirado"),
    ("BP_Mirado_A_03_C", "Mirado"),
    ("BP_Mirado_A_03_Esports_C", "Mirado"),
    ("BP_Mirado_Open_03_C", "Mirado"),
    ("BP_Mirado_Open_04_C", "Mirado"),
    ("BP_Mirado_Open_05_C", "Mirado"),
    ("BP_MolotovFireDebuff_C", "Molotov"),
    ("BP_Motorbike_04_C", "Motorcycle"),
    ("BP_Motorbike_04_Desert_C", "Motorcycle"),
    ("BP_Motorbike_04_SideCar_C", "Motorcycle"),
    ("BP_Motorbike_04_SideCar_Desert_C", "Motorcycle"),
    ("BP_Motorbike_Solitario_C", "Motorcycle"),
    ("BP_Motorglider_C", "Glider"),
    ("BP_Motorglider_Green_C", "Glider"),
    ("BP_Niva_01_C", "Zima"),
    ("BP_Niva_02_C", "Zima"),
    ("BP_Niva_03_C", "Zima"),
    ("BP_Niva_04_C", "Zima"),
    ("BP_Niva_05_C", "Zima"),
    ("BP_Niva_06_C", "Zima"),
    ("BP_Niva_07_C", "Zima"),
    ("BP_Niva_Esports_C", "Zima"),
    ("BP_PickupTruck_A_01_C", "Pickup"),
    ("BP_PickupTruck_A_02_C", "Pickup"),
    ("BP_PickupTruck_A_03_C", "Pickup"),
    ("BP_PickupTruck_A_04_C", "Pickup"),
    ("BP_PickupTruck_A_05_C", "Pickup"),
    ("BP_PickupTruck_A_esports_C", "Pickup"),
    ("BP_PickupTruck_B_01_C", "Pickup"),
    ("BP_PickupTruck_B_02_C", "Pickup"),
    ("BP_PickupTruck_B_03_C", "Pickup"),
    ("BP_PickupTruck_B_04_C", "Pickup"),
    ("BP_PickupTruck_B_05_C", "Pickup"),
    ("BP_Pillar_Car_C", "Police"),
    ("BP_PonyCoupe_C", "Pony"),
    ("BP_Porter_C", "Porter"),
    ("BP_Scooter_01_A_C", "Scooter"),
    ("BP_Scooter_02_A_C", "Scooter"),
    ("BP_Scooter_03_A_C", "Scooter"),
    ("BP_Scooter_04_A_C", "Scooter"),
    ("BP_Snowbike_01_C", "Snowbike"),
    ("BP_Snowbike_02_C", "Snowbike"),
    ("BP_Snowmobile_01_C", "Snowmobile"),
    ("BP_Snowmobile_02_C", "Snowmobile"),
    ("BP_Snowmobile_03_C", "Snowmobile"),
    ("BP_Spiketrap_C", "Spike-Trap"),
    ("BP_TslGasPump_C", "Gas-Pump"),
    ("BP_TukTukTuk_A_01_C", "Tukshai"),
    ("BP_TukTukTuk_A_02_C", "Tukshai"),
    ("BP_TukTukTuk_A_03_C", "Tukshai"),
    ("BP_Van_A_01_C", "Van"),
    ("BP_Van_A_02_C", "Van"),
    ("BP_Van_A_03_C", "Van"),
    ("BattleRoyaleModeController_Chimera_C", "Bluezone"),
    ("BattleRoyaleModeController_Def_C", "Bluezone"),
    ("BattleRoyaleModeController_Desert_C", "Bluezone"),
    ("BattleRoyaleModeController_DihorOtok_C", "Bluezone"),
    ("BattleRoyaleModeController_Heaven_C", "Bluezone"),
    ("BattleRoyaleModeController_Kiki_C", "Bluezone"),
    ("BattleRoyaleModeController_Savage_C", "Bluezone"),
    ("BattleRoyaleModeController_Summerland_C", "Bluezone"),
    ("BattleRoyaleModeController_Tiger_C", "Bluezone"),
    ("BlackZoneController_Def_C", "Blackzone"),
    ("Bluezonebomb_EffectActor_C", "Bluezone Grenade"),
    ("Boat_PG117_C", "PG-117"),
    ("Buff_DecreaseBreathInApnea_C", "Drowning"),
    ("Buggy_A_01_C", "Buggy"),
    ("Buggy_A_02_C", "Buggy"),
    ("Buggy_A_03_C", "Buggy"),
    ("Buggy_A_04_C", "Buggy"),
    ("Buggy_A_05_C", "Buggy"),
    ("Buggy_A_06_C", "Buggy"),
    ("Carepackage_Container_C", "Care Package"),
    ("Dacia_A_01_v2_C", "Dacia"),
    ("Dacia_A_01_v2_snow_C", "Dacia"),
    ("Dacia_A_02_v2_C", "Dacia"),
    ("Dacia_A_03_v2_C", "Dacia"),
    ("Dacia_A_03_v2_Esports_C", "Dacia"),
    ("Dacia_A_04_v2_C", "Dacia"),
    ("DroppedItemGroup", "Object-Fragments"),
    ("EmergencyAircraft_Tiger_C", "Emergency Aircraft"),
    ("Jerrycan", "Jerrycan"),
    ("JerrycanFire", "Jerrycan"),
    ("Lava", "Lava"),
    ("Mortar_Projectile_C", "Mortar"),
    ("None", "None"),
    ("PG117_A_01_C", "PG-117"),
    ("PanzerFaust100M_Projectile_C", "Panzerfaust"),
    ("PlayerFemale_A_C", "Player"),
    ("PlayerMale_A_C", "Player"),
    ("ProjC4_C", "C4"),
    ("ProjGrenade_C", "Frag-Grenade"),
    ("ProjIncendiary_C", "Incendiary"),
    ("ProjMolotov_C", "Molotov"),
    ("ProjMolotov_DamageField_Direct_C", "Molotov"),
    ("ProjStickyGrenade_C", "Sticky-Bomb"),
    ("RacingDestructiblePropaneTankActor_C", "Propane Tank"),
    ("RacingModeContorller_Desert_C", "Bluezone"),
    ("RacingModeContorller_Desert_C", "Bluezone"),
    ("TslGameModeBase_BattleRoyaleBP_C", "Bluezone"),
    ("RedZoneBomb_C", "Redzone"),
    ("RedZoneBombingField", "Redzone"),
    ("RedZoneBombingField_Def_C", "Redzone"),
    ("SandStormBuff_BP_C", "Sandstorm"),
    ("TslDestructibleSurfaceManager", "Destructible Surface"),
    ("TslPainCausingVolume", "Lava"),
    ("Uaz_A_01_C", "UAZ"),
    ("Uaz_Armored_C", "UAZ"),
    ("Uaz_B_01_C", "UAZ"),
    ("Uaz_B_01_esports_C", "UAZ"),
    ("Uaz_C_01_C", "UAZ"),
    ("UltAIPawn_Base_Female_C", "Player"),
    ("UltAIPawn_Base_Male_C", "Player"),
    ("WeapACE32_C", "ACE32"),
    ("WeapAK47_C", "AKM"),
    ("WeapAUG_C", "AUG-A3"),
    ("WeapAWM_C", "AWM"),
    ("WeapBerreta686_C", "S686"),
    ("WeapBerylM762_C", "Beryl M762"),
    ("WeapBizonPP19_C", "Bizon"),
    ("WeapCowbarProjectile_C", "Crowbar"),
    ("WeapCowbar_C", "Crowbar"),
    ("WeapCrossbow_1_C", "Crossbow"),
    ("WeapDP12_C", "DBS"),
    ("WeapDP28_C", "DP-28"),
    ("WeapDesertEagle_C", "Deagle"),
    ("WeapDragunov_C", "Dragunov"),
    ("WeapDuncansHK416_C", "M416"),
    ("WeapFNFal_C", "SLR"),
    ("WeapG18_C", "P18C"),
    ("WeapG36C_C", "G36C"),
    ("WeapGroza_C", "Groza"),
    ("WeapHK416_C", "M416"),
    ("WeapJS9_C", "JS9"),
    ("WeapJuliesKar98k_C", "Kar98k"),
    ("WeapK2_C", "K2"),
    ("WeapKar98k_C", "Kar98k"),
    ("WeapL6_C", "Lynx"),
    ("WeapLunchmeatsAK47_C", "AKM"),
    ("WeapM16A4_C", "M16A4"),
    ("WeapM1911_C", "P1911"),
    ("WeapM249_C", "M249"),
    ("WeapM24_C", "M24"),
    ("WeapM9_C", "P92"),
    ("WeapMG3_C", "MG3"),
    ("WeapMP5K_C", "MP5K"),
    ("WeapMP9_C", "MP9"),
    ("WeapMacheteProjectile_C", "Machete"),
    ("WeapMachete_C", "Machete"),
    ("WeapMadsQBU88_C", "QBU88"),
    ("WeapMini14_C", "Mini-14"),
    ("WeapMk12_C", "Mk12"),
    ("WeapMk14_C", "Mk14"),
    ("WeapMk47Mutant_C", "Mk47-Mutant"),
    ("WeapMosinNagant_C", "Mosin-Nagant"),
    ("WeapNagantM1895_C", "R1895"),
    ("WeapOriginS12_C", "O12"),
    ("WeapP90_C", "P90"),
    ("WeapPanProjectile_C", "Pan"),
    ("WeapPan_C", "Pan"),
    ("WeapPanzerFaust100M1_C", "Panzerfaust"),
    ("WeapQBU88_C", "QBU88"),
    ("WeapQBZ95_C", "QBZ95"),
    ("WeapRhino_C", "R45"),
    ("WeapSCAR-L_C", "SCAR-L"),
    ("WeapSKS_C", "SKS"),
    ("WeapSaiga12_C", "S12K"),
    ("WeapSawnoff_C", "Sawed-off"),
    ("WeapSickleProjectile_C", "Sickle"),
    ("WeapSickle_C", "Sickle"),
    ("WeapThompson_C", "Tommy-Gun"),
    ("WeapTurret_KillTruck_Main_C", "Kill Truck Turret"),
    ("WeapUMP_C", "UMP9"),
    ("WeapUZI_C", "Micro-Uzi"),
    ("WeapVSS_C", "VSS"),
    ("WeapVector_C", "Vector"),
    ("WeapWin94_C", "Win94"),
    ("WeapWinchester_C", "S1897"),
    ("Weapvz61Skorpion_C", "Skorpion"),
    ("Item_Weapon_AK47_C", "AKM"),
    ("Item_Weapon_AUG_C", "AUG A3"),
    ("Item_Weapon_AWM_C", "AWM"),
    ("Item_Weapon_Apple_C", "Apple"),
    ("Item_Weapon_Berreta686_C", "S686"),
    ("Item_Weapon_BerylM762_C", "Beryl M762"),
    ("Item_Weapon_BizonPP19_C", "Bizon"),
    ("Item_Weapon_BlueChipDetector_C", "Blue Chip Detector"),
    ("Item_Weapon_BluezoneGrenade_C", "Bluezone Grenade"),
    ("Item_Weapon_C4_C", "C4"),
    ("Item_Weapon_Cowbar_C", "Crowbar"),
    ("Item_Weapon_Crossbow_C", "Crossbow"),
    ("Item_Weapon_DP12_C", "DBS"),
    ("Item_Weapon_DP28_C", "DP-28"),
    ("Item_Weapon_DecoyGrenade_C", "Decoy Grenade"),
    ("Item_Weapon_DesertEagle_C", "Deagle"),
    ("Item_Weapon_Dragunov_C", "Dragunov"),
    ("Item_Weapon_Drone_C", "Drone"),
    ("Item_Weapon_Duncans_M416_C", "M416"),
    ("Item_Weapon_FNFal_C", "SLR"),
    ("Item_Weapon_FlareGun_C", "Flare Gun"),
    ("Item_Weapon_FlashBang_C", "Flashbang"),
    ("Item_Weapon_G18_C", "P18C"),
    ("Item_Weapon_G36C_C", "G36C"),
    ("Item_Weapon_Grenade_C", "Frag Grenade"),
    ("Item_Weapon_Grenade_Warmode_C", "Frag Grenade"),
    ("Item_Weapon_Groza_C", "Groza"),
    ("Item_Weapon_HK416_C", "M416"),
            ("Item_Weapon_JS9_C", "JS9"),
            ("Item_Weapon_K2_C", "K2"),
            ("Item_Weapon_Kar98k_C", "Kar98k"),
            ("Item_Weapon_L6_C", "Lynx AMR"),
            ("Item_Weapon_M16A4_C", "M16A4"),
            ("Item_Weapon_M1911_C", "P1911"),
            ("Item_Weapon_M249_C", "M249"),
            ("Item_Weapon_M24_C", "M24"),
            ("Item_Weapon_M79_C", "M79"),
            ("Item_Weapon_M9_C", "P92"),
            ("Item_Weapon_MG3_C", "MG3"),
            ("Item_Weapon_MP5K_C", "MP5K"),
            ("Item_Weapon_MP9_C", "MP9"),
            ("Item_Weapon_Machete_C", "Machete"),
            ("Item_Weapon_Mads_QBU88_C", "QBU88"),
            ("Item_Weapon_Mini14_C", "Mini 14"),
            ("Item_Weapon_Mk12_C", "Mk12"),
            ("Item_Weapon_Mk14_C", "Mk14 EBR"),
            ("Item_Weapon_Mk47Mutant_C", "Mk47 Mutant"),
            ("Item_Weapon_Molotov_C", "Molotov Cocktail"),
            ("Item_Weapon_Mortar_C", "Mortar"),
            ("Item_Weapon_Mosin_C", "Mosin-Nagant"),
            ("Item_Weapon_NagantM1895_C", "R1895"),
            ("Item_Weapon_OriginS12_C", "O12"),
            ("Item_Weapon_P90_C", "P90"),
            ("Item_Weapon_Pan_C", "Pan"),
            ("Item_Weapon_PanzerFaust100M_C", "Panzerfaust"),
            ("Item_Weapon_QBU88_C", "QBU88"),
            ("Item_Weapon_QBZ95_C", "QBZ95"),
            ("Item_Weapon_Rhino_C", "R45"),
            ("Item_Weapon_Rock_C", "Rock"),
            ("Item_Weapon_SCAR-L_C", "SCAR-L"),
            ("Item_Weapon_SKS_C", "SKS"),
            ("Item_Weapon_Saiga12_C", "S12K"),
            ("Item_Weapon_Sawnoff_C", "Sawed-off"),
            ("Item_Weapon_Sickle_C", "Sickle"),
            ("Item_Weapon_SmokeBomb_C", "Smoke Grenade"),
            ("Item_Weapon_Snowball_C", "Snowball"),
            ("Item_Weapon_SpikeTrap_C", "Spike Trap"),
            ("Item_Weapon_Spotter_Scope_C", "Spotter Scope"),
            ("Item_Weapon_StickyGrenade_C", "Sticky Bomb"),
            ("Item_Weapon_StunGun_C", "Stun Gun"),
            ("Item_Weapon_TacPack_C", "Tactical Pack"),
            ("Item_Weapon_Thompson_C", "Tommy Gun"),
            ("Item_Weapon_TraumaBag_C", "Trauma Bag"),
            ("Item_Weapon_UMP_C", "UMP9"),
            ("Item_Weapon_UZI_C", "Micro Uzi"),
            ("Item_Weapon_VSS_C", "VSS"),
            ("Item_Weapon_Vector_C", "Vector"),
            ("Item_Weapon_Win1894_C", "Win94"),
            ("Item_Weapon_Winchester_C", "S1897"),
            ("Item_Weapon_vz61Skorpion_C", "Skorpion"),
            ("Item_Weapon_ACE32_C", "ACE32"),
            ("Item_Weapon_FAMASG2_C", "Famas"),
];
