pub const WEAPON_TYPE: [(&str, &str); 53] = [
    ("Lynx AMR", "HP Sniper"),
    ("AWM", "HP Sniper"),
    ("Kar98k", "Sniper"),
    ("Mosin Nagant", "Sniper"),
    ("M24", "Sniper"),
    ("Win94", "Sniper"),
    ("MK14", "DMR"),
    ("Dragunov", "DMR"),
    ("SLR", "DMR"),
    ("SKS", "DMR"),
    ("MK12", "DMR"),
    ("Mini-14", "DMR"),
    ("QBU", "DMR"),
    ("VSS", "DMR"),
    ("DP-28", "LMG"),
    ("M249", "LMG"),
    ("MG3", "LMG"),
    ("Mutant MK47", "Assault Rifle"),
    ("AKM", "Assault Rifle"),
    ("Groza", "Assault Rifle"),
    ("Beryl M762", "Assault Rifle"),
    ("ACE32", "Assault Rifle"),
    ("M16A4", "Assault Rifle"),
    ("QBZ", "Assault Rifle"),
    ("SCAR-L", "Assault Rifle"),
    ("AUG-A3", "Assault Rifle"),
    ("G36C", "Assault Rifle"),
    ("K2", "Assault Rifle"),
    ("M416", "Assault Rifle"),
    ("FAMAS", "Assault Rifle"),
    ("UMP45", "SMG"),
    ("Tommy Gun", "SMG"),
    ("PP-19 Bizon", "SMG"),
    ("P90", "SMG"),
    ("MP5K", "SMG"),
    ("MP9", "SMG"),
    ("JS9", "SMG"),
    ("Vector", "SMG"),
    ("Micro UZI", "SMG"),
    ("O-12", "Shotgun"),
    ("DBS", "Shotgun"),
    ("S1897", "Shotgun"),
    ("S686", "Shotgun"),
    ("S12K", "Shotgun"),
    ("Sawed-Off", "Shotgun"),
    ("R45", "Pistol"),
    ("R1895", "Pistol"),
    ("Deagle", "Pistol"),
    ("P1911", "Pistol"),
    ("P92", "Pistol"),
    ("P18C", "Pistol"),
    ("Skorpion", "Pistol"),
    ("Crossbow", "Crossbow"),
];
